# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddCity.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewCity(object):
    def setupUi(self, NewCity):

        CitiesIcon = QtGui.QIcon()
        CitiesIcon.addPixmap(QtGui.QPixmap("UI/icon/city"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewCity.setObjectName("NewCity")
        NewCity.resize(400, 130)
        self.CityID = QtWidgets.QLabel(NewCity)
        self.CityID.setGeometry(QtCore.QRect(30, 20, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CityID.setFont(font)
        self.CityID.setObjectName("CityID")
        self.CityTitle = QtWidgets.QLabel(NewCity)
        self.CityTitle.setGeometry(QtCore.QRect(30, 50, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CityTitle.setFont(font)
        self.CityTitle.setObjectName("CityTitle")
        self.CityIDField = QtWidgets.QLineEdit(NewCity)
        self.CityIDField.setGeometry(QtCore.QRect(130, 20, 100, 20))
        self.CityIDField.setObjectName("CityIDField")
        self.CityTitleField = QtWidgets.QLineEdit(NewCity)
        self.CityTitleField.setGeometry(QtCore.QRect(130, 50, 191, 20))
        self.CityTitleField.setObjectName("CityTitleField")
        self.addCityBTN = QtWidgets.QPushButton(NewCity)
        self.addCityBTN.setGeometry(QtCore.QRect(240, 100, 75, 25))
        self.addCityBTN.setObjectName("addCityBTN")
        self.ReturnBTN = QtWidgets.QPushButton(NewCity)
        self.ReturnBTN.setGeometry(QtCore.QRect(320, 100, 75, 25))
        self.ReturnBTN.setObjectName("ReturnBTN")
        self.CityIDField.setEnabled(False)

        self.retranslateUi(NewCity)
        QtCore.QMetaObject.connectSlotsByName(NewCity)

    def retranslateUi(self, NewCity):
        _translate = QtCore.QCoreApplication.translate
        NewCity.setWindowTitle(_translate("NewCity", "Добавить новый город"))
        self.CityID.setText(_translate("NewCity", "Код города:"))
        self.CityTitle.setText(_translate("NewCity", "Наименование:"))
        self.addCityBTN.setText(_translate("NewCity", "Добавить"))
        self.ReturnBTN.setText(_translate("NewCity", "Отмена"))
