# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddObject.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewObject(object):
    def setupUi(self, NewObject):

        ObjectIcon = QtGui.QIcon()
        ObjectIcon.addPixmap(QtGui.QPixmap("UI/icon/organization.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewObject.setObjectName("NewObject")
        NewObject.resize(400, 130)
        self.ObjectID = QtWidgets.QLabel(NewObject)
        self.ObjectID.setGeometry(QtCore.QRect(30, 20, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ObjectID.setFont(font)
        self.ObjectID.setObjectName("ObjectID")
        self.ObjectTitle = QtWidgets.QLabel(NewObject)
        self.ObjectTitle.setGeometry(QtCore.QRect(30, 50, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ObjectTitle.setFont(font)
        self.ObjectTitle.setObjectName("ObjectTitle")
        self.ObjectIDField = QtWidgets.QLineEdit(NewObject)
        self.ObjectIDField.setGeometry(QtCore.QRect(130, 20, 100, 20))
        self.ObjectIDField.setObjectName("ObjectIDField")
        self.ObjectTitleField = QtWidgets.QLineEdit(NewObject)
        self.ObjectTitleField.setGeometry(QtCore.QRect(130, 50, 191, 20))
        self.ObjectTitleField.setObjectName("ObjectTitleField")
        self.addObjectBTN = QtWidgets.QPushButton(NewObject)
        self.addObjectBTN.setGeometry(QtCore.QRect(240, 100, 75, 25))
        self.addObjectBTN.setObjectName("addObjectBTN")
        self.ReturnBTN = QtWidgets.QPushButton(NewObject)
        self.ReturnBTN.setGeometry(QtCore.QRect(320, 100, 75, 25))
        self.ReturnBTN.setObjectName("ReturnBTN")
        self.ObjectIDField.setEnabled(False)

        self.retranslateUi(NewObject)
        QtCore.QMetaObject.connectSlotsByName(NewObject)

    def retranslateUi(self, NewObject):
        _translate = QtCore.QCoreApplication.translate
        NewObject.setWindowTitle(_translate("NewObject", "Добавить новый объект"))
        self.ObjectID.setText(_translate("NewObject", "Код объекта:"))
        self.ObjectTitle.setText(_translate("NewObject", "Наименование:"))
        self.addObjectBTN.setText(_translate("NewObject", "Добавить"))
        self.ReturnBTN.setText(_translate("NewObject", "Отмена"))
